name: Build and Deploy TEST

env:
  RESOLVE_OUTPUT_PATH: ${{ github.workspace }}/.output/resolve
  MAINTENANCE_OUTPUT_PATH: ${{ github.workspace }}/.output/maintenance
  DOTNET_VERSION: "3.1.100"

on:
  push:
    branches:
      - main
      - 'issues/2-workflow'
  pull_request:
    branches: [ main ]

jobs:
  provision-infra:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout branch'
        uses: actions/checkout@v2

      - name: 'Login with Azure'
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      - name: 'Run ARM Templates on TEST Environment'
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: 'shortlink-test-backend'
          template: src/HexMaster.ShortLink.Backend.Deployment/azuredeploy.json

  compile:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout branch'
        uses: actions/checkout@v2

      - name: Setup Dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish Resolve Function
        run: dotnet publish src/HexMaster.ShortLink.Resolver/HexMaster.ShortLink.Resolver.csproj --configuration Release --output ${{ env.RESOLVE_OUTPUT_PATH }}

      - name: Publish Maintenance Function
        run: dotnet publish src/HexMaster.ShortLink.Maintenance/HexMaster.ShortLink.Maintenance.csproj --configuration Release --output ${{ env.MAINTENANCE_OUTPUT_PATH }}

      - name: Package Resolve functions
        uses: actions/upload-artifact@v1
        with:
            name: resolve-functions
            path: ${{ env.RESOLVE_OUTPUT_PATH }}

      - name: Package Maintenance functions
        uses: actions/upload-artifact@v1
        with:
            name: maintenance-functions
            path: ${{ env.MAINTENANCE_OUTPUT_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: [provision-infra,compile]

    steps:
      - name: Download Resolve Functions
        uses: actions/download-artifact@v1
        with:
            name: resolve-functions
            path: ${{ env.RESOLVE_OUTPUT_PATH }}

      - name: Download Maintenance Functions
        uses: actions/download-artifact@v1
        with:
            name: maintenance-functions
            path: ${{ env.MAINTENANCE_OUTPUT_PATH }}

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      - name: "Deploy Resolve Functions"
        uses: Azure/functions-action@v1
        with:
            app-name: 'shortlink-test-resolve-app'
            package: ${{ env.RESOLVE_OUTPUT_PATH }}

      - name: "Deploy Maintenance Functions"
        uses: Azure/functions-action@v1
        with:
            app-name: 'shortlink-test-maintenance-app'
            package: ${{ env.MAINTENANCE_OUTPUT_PATH }}